#########################################################################
# Title:            Sandbox: Restreamer                                 #
# Author(s):        Derek Z, JigSawFr                                   #
# URL:              https://github.com/saltyorg/Sandbox                 #
# URL:              https://github.com/linuxserver/docker-duplicati     #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Add hardware acceleration devices
  ansible.builtin.include_tasks: "{{ mod_resources_tasks_path }}/docker/set_docker_devices_variable_list.yml"
  vars:
    docker_device_binds_list:
      - { host_path: "/dev/dri", container_path: "/dev/dri" }
      - { host_path: "/dev/video0", container_path: "/dev/video0" }
      - { host_path: "/dev/snd", container_path: "/dev/snd" }

- name: Debug Docker container creation 
  ansible.builtin.include_tasks: "{{ mod_resources_tasks_path }}/docker/debug_docker_create_container.yml"
  when: lookup('file', mod_resources_tasks_path + '/docker/debug_docker_create_container.yml', errors='ignore')

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"